#version: '3.8'

services:
  database:
    image: postgres:15
    container_name: fractals-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Banana021104
      POSTGRES_DB: fractals_db
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: fractals-app
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/fractals_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Banana021104
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./logs:/app/logs

volumes:
  db-data:
